main/blog/urls.py
from django.urls    import path
from .views         import (home,
                            post_create,
                            post_detail,
                            post_update,
                            post_delete,
                            comment_create,
                            comment_delete,
                            book_search,
                            kyobo,
                            KyoboApiView,
                            CovidApiView,
                            BoardView,
                            BoardDetailView,
                            SchedulerViewApi,
                            SchedulerViewDetailApi,
                            )

urlpatterns = [
    path(''                             , home, name='home'),
    path('create/'                      , post_create, name='create'),
    path('<int:pk>/'                    , post_detail, name='detail'),
    path('<int:pk>/update/'             , post_update, name='update'),
    path('<int:pk>/delete/'             , post_delete, name='delete'),
    path('comment/<int:pk>/create/'     , comment_create, name='comment_create'),  # 댓글 작성 부분 URL 라우팅
    path('comment/<int:pk>/delete/'     , comment_delete, name='comment_delete'),  # 댓글 삭제 부분 URL 라우팅
    path('book_search/'                 , book_search, name='book_search'),
    path('kyobo/'                       , kyobo, name='kyobo'),
    path('book_api/'                    , KyoboApiView.as_view(), name='book_api'),
    path('covid_api/'                   , CovidApiView.as_view(), name='covid_api'),
    path('board'                        , BoardView.as_view()),
    path('board/<int:memo_id>'          , BoardDetailView.as_view()),
    path('scheduler'                    , SchedulerViewApi.as_view()),
    path('scheduler/<int:scheduler_id>' , SchedulerViewDetailApi.as_view()),
]

main/main/urls.py
from django.urls    import path, include

urlpatterns = [
    path('blog/'  , include('blog.urls')),
    path('user/'  , include('user.urls')),
]

main/blog/models.py
from django.db import models

class Post(models.Model):
    title      = models.CharField(max_length=100, blank=True, null=True)
    author     = models.CharField(max_length=10, blank=True, null=True)
    date       = models.DateField(blank=True, null=True)
    content    = models.TextField(blank=True, null=True)
    writer     = models.TextField(max_length=255, blank=False, null=False)

    # Meta 클래스를 재정의해서 옵션 설정가능.
    class Meta:
        app_label = 'blog'
        db_table  = 'post'


# 댓글 테이블
class Comment(models.Model):
    id               = models.AutoField(primary_key=True)
    writer           = models.TextField(max_length=255, blank=False, null=False)
    date             = models.DateField(blank=True, null=True)
    content          = models.TextField(blank=True, null=True)
    approved_comment = models.BooleanField(default=False)

    # Post의 Primary Key를 외래키로 지정해 놓는다.
    # 이런식으로, 특정 post 안의 댓글 모델을 구현한다.
    # 자세한 내용은 데이터베이스 1~2 정규화 내용 참조.
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')

    def approve(self):
        self.approved_comment = True
        self.save()

    class Meta:
        app_label = 'blog'  # 이런식으로, 해당 모델이 속한 앱을 명시해주어야 한다.
        db_table = 'comment'
        # managed = False # Managed 플래그는, 모델이 갱신되도, Database 테이블은 갱신이 안되게하는 옵션임. 


class Book(models.Model):
    num            = models.AutoField(primary_key=True)
    title          = models.CharField(max_length=100, blank=True, null=True)
    author         = models.CharField(max_length=100, blank=True, null=True)
    image          = models.CharField(max_length=250, blank=True, null=True)
    url            = models.CharField(max_length=250, blank=True, null=True)
    original_price = models.CharField(max_length=250, blank=True, null=True)
    sale_price     = models.CharField(max_length=250, blank=True, null=True)

    class Meta:
        app_label = 'blog'
        db_table  = 'book'

class Covid(models.Model):
    area    = models.CharField(max_length=100 ,    blank=True , null=True)
    country = models.CharField(max_length=200 ,    blank=True , null=True)
    patient = models.IntegerField(max_length=500 , blank=True , null=True)
    dead    = models.IntegerField(max_length=500 , blank=True , null=True)

    class Meta:
        db_table = 'covids'

class KoreaCovid(models.Model):
    area     = models.CharField(max_length=100, blank=True , null=True)
    patient  = models.CharField(max_length=250, blank=True , null=True)
    increase = models.CharField(max_length=250, blank=True , null=True)

    class Meta:
        db_table = "korea_covids"

class Memo(models.Model):
    title   = models.CharField(max_length=200 , blank=True , null = True)
    content = models.CharField(max_length=500 , blank=True , null = True)

    class Meta:
        db_table = "memos"

class Scheduler(models.Model):
    start_date = models.DateTimeField(max_length=250)
    end_date   = models.DateTimeField(max_length=250)
    text       = models.CharField(max_length=250 , blank=False)

    class Meta:
        db_table ='schedulers'

main/blog/forms.py
from django  import forms
from .models import Post, Comment


# 포스트 내용을 받을 Form을 정의해줌.
class PostForm(forms.ModelForm):
    class Meta:
        model   = Post
        fields  = ['title', 'author', 'content']

        widgets = {
            'title': forms.TextInput(
                attrs={'class'       : 'form-control',
                       'style'       : 'width:200px; margin:20px;',
                       'placeholder' : '제목을 입력하세요.'}
            ),
            'author': forms.TextInput(
                attrs={'class'       : 'form-control',
                       'style'       : 'width:200px; margin:20px;',
                       'placeholder' : '저자를 입력하세요.'}
            ),
            'content': forms.Textarea(
                attrs={'class'       : 'form-control',
                       'style'       : 'width:100%; height:50%; rows=3; margin:20px;',
                       'placeholder' : '내용을 입력하세요.'}
            )
        }


# 댓글 내용을 받을 Form을 정의해줌.
class CommentForm(forms.ModelForm):
    class Meta:
        model   = Comment
        fields  = ['content']

        widgets = {
            'content': forms.Textarea(
                attrs={'class'       : 'form-control',
                       'style'       : 'width:90%; height:10%; rows=1; margin:1em;',
                       'placeholder' : '내용을 입력하세요.'}
            )
        }

main/blog/views.py
import json
import urllib.request

from django.shortcuts      import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models      import Count, Q , Sum
from django.views          import View
from django.http           import HttpResponse, JsonResponse

from datetime              import *
from main.my_settings      import CLIENT_ID, CLIENT_SECRET
from user.decorators       import login_required
from .forms                import PostForm, CommentForm
from .models               import (Post,
                                   Book,
                                   Comment,
                                   Covid,
                                   KoreaCovid,
                                   Memo,
                                   Scheduler)

@login_required
def home(request):
    posts = Post.objects.all()  # 모든 Border 테이블의 모든 object들을 br에 저장하라
    # 검색 부분
    search = request.GET.get('search', '')  # GET request의 인자중에 b 값이 있으면 가져오고, 없으면 빈 문자열 넣기
    if search:  # search 에 값이 들어있으면 true
        posts = posts.filter(title__icontains=search)  # 의 title이 contains br의 title에 포함

    # 페이지 부분
    page = request.GET.get('page', 1)
    paginator = Paginator(posts, 5)  # Show 5 contacts per page

    # posts = paginator.get_page(page)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'index.html', {'posts': posts, 'search_data': search})


# 로그인 한 사람만 접근 가능하도록 login_required decorator 추가.
# 해당 함수는, 브라우저로 부터 제목, 저자, 내용을 받아서 포스트를 저장하는 함수이다. 
@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)

        # 로그인된 상태 및 form으로 제출한 내용을 체크해서 전부 유효한 경우, 게시물을 생성한다.
        if request.session['user'] is not None and form.is_valid():
            # form에서 바로 값을 추가하는것은 불가해서, 먼저 commit=False 옵션을 줘서 Save 한 뒤, 
            # post라는 변수로 값을 받아서 값을 써주고 다시 save해주어야 한다.
            post = form.save(commit=False)
            post.writer = request.session['user']
            post.date = datetime.today()  # DateTime 필드에 날짜를 저장할때는 아래와 같이 파이썬 내장 모듈인 datatime을 사용해서 날짜지정이 가능하다.
            post.save()
            return redirect('home')

    # POST 요청이 아닌 경우 단순히 Form 태그만 리턴한다.
    form = PostForm()

    return render(request, 'postcreate.html', {'form': form})


# 포스트 내용을 자세히 보여주는 페이지
@login_required
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    # 아래와 같이, 포스트의 primary키를 이용해서, 해당 포스트에 속한 댓글들을 가져온다.
    comments = Comment.objects.filter(post=pk)
    comment_form = CommentForm()
    return render(request, 'postdetail.html', {'post': post, 'comments': comments, 'comment_form': comment_form})


@login_required
def post_update(request, pk):
    post = get_object_or_404(Post, pk=pk)

    # 게시글(포스트) 작성자가 아닌경우, 게시글(포스트) 수정을 불가능하게 함. 
    # 게시글 테이블에 저장된 작성자와 현재 세션의 작성자를 비교하는 방식으로 구현하였습니다.
    if request.session['user'] is not None and post.writer != request.session['user']:
        return redirect('home')

    # 갱신된 게시글(포스트)를 저장하는 부분입니다.
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('home')

    form = PostForm(instance=post)

    return render(request, 'postupdate.html', {'form': form})

@login_required
def post_delete(request, pk):
    post = Post.objects.get(pk=pk)

    # 게시글(포스트) 작성자가 아닌경우, 게시글(포스트) 삭제를 불가능하게 함. 
    # 게시글 테이블에 저장된 작성자와 현재 세션의 작성자를 비교하는 방식으로 구현하였습니다.
    if request.session['user'] is not None and post.writer == request.session['user']:
        post.delete()

    return redirect('home')

@login_required
def comment_create(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        # 댓글 내용을 받는 부분
        form = CommentForm(request.POST)
        if form.is_valid():
            # form에서 바로 값을 추가하는것은 불가해서, 먼저 commit=False 옵션을 줘서 Save 한 뒤,
            # comment라는 변수로 값을 받아서 값을 써주고 다시 save해주어야 한다.
            comment = form.save(commit=False)
            comment.writer = request.session['user']
            comment.post = post
            comment.date = datetime.today()  # DateTime 필드에 날짜를 저장할때는 아래와 같이 파이썬 내장 모듈인 datatime을 사용해서 날짜지정이 가능하다.
            comment.save()
            return redirect('detail', pk=comment.post.pk)

    form = CommentForm()
    return redirect('detail')


@login_required
def comment_delete(request, pk):
    comment = get_object_or_404(Comment, pk=pk)

    # 댓글 작성자가 아닌경우, 댓글 삭제를 불가능하게 함. 
    # 댓글 테이블에 저장된 작성자와 현재 세션의 작성자를 비교하는 방식으로 구현
    if request.session['user'] is not None and comment.writer == request.session['user']:
        comment.delete()

    return redirect('detail', pk=comment.post.pk)


def book_search(request):
    if request.method == 'GET':

        input_data    = request.GET.get('input_search',None)
        encText       = urllib.parse.quote("{}".format(input_data))
        if input_data is None:
            # print('데이터가없습니다.')
            encText = urllib.parse.quote("Django")
        url = "https://openapi.naver.com/v1/search/book?query=" + encText  # json 결과
        book_api_request = urllib.request.Request(url)
        book_api_request.add_header("X-Naver-Client-Id"     , CLIENT_ID)
        book_api_request.add_header("X-Naver-Client-Secret" , CLIENT_SECRET)
        response = urllib.request.urlopen(book_api_request)
        if (response.getcode() == 200):
            response_body = response.read()
            items         = json.loads(response_body
                                       .decode('utf-8')).get('items')

            return render(request, 'book_search.html', {'items': items})

def kyobo(request):
    kyobo_book = Book.objects.all()

    return render(request, 'kyobo.html', {'kyobo_list': kyobo_book})


class KyoboApiView(View):
    def get(self, request):

        try:
            keyword = request.GET.get('keyword', None)
            if keyword:
                book_data    = Book.objects.filter(Q(author__icontains=keyword)).all().values()
                search_count = book_data.count()

                return JsonResponse(
                    {'data' : {
                        'book_count' : search_count,
                        'books'      : list(book_data)
                    }}, status=200)

            kyobo       = Book.objects.values()
            kyobo_count = Book.objects.count()

            return JsonResponse(
                {'data' : {
                    'book_count' : kyobo_count,
                    'books'      : list(kyobo)
                }}, status=200)

        except Book.DoesNotExist:
            return JsonResponse({'message': 'Not found'}, status=400)

        except TypeError:
            return JsonResponse({'message': 'error'}, status=400)

class CovidApiView(View):
    def get(self, request):
        try:
            query = request.GET.get('keyword',None) # 코로나 데이터 검색 
            if query:
                world_data           = Covid.objects.filter(Q(area__icontains=query) | Q(country__icontains=query)).all()
                korea_data          = KoreaCovid.objects.filter(Q(area__icontains=query)).all()
                world_patient_count = world_data.count()
                korea_patient_count = korea_data.count()

                data = {
                    'korea_count' : korea_patient_count,
                    'world_count' : world_patient_count,
                    'world_data'  : [{
                            'id'      : world.id,
                            'area'    : world.area,
                            'country' : world.country,
                            'patient' : world.patient,
                            'dead'    : world.dead,
                    } for world in world_data],
                    'korea_data' : [{
                            'id'      : korea.id,
                            'area'    : korea.area,
                            'patient' : korea.patient,
                    } for korea in korea_data],
                }

                return JsonResponse({"data" :data},status=200)

            country_covid     = Covid.objects.values()
            korea_covid       = KoreaCovid.objects.values()
            korea_covid_count = KoreaCovid.objects.all().aggregate(Sum('patient'))

            return JsonResponse({'data' : {
                                    'korea_covid_count' : korea_covid_count,
                                    'korea_covid'       : list(korea_covid),
                                    'country_covid'     : list(country_covid),
                                }}, status=200)

        except Covid.DoesNotExist:
            return JsonResponse({'message': 'Not found'}, status=400)

        except TypeError:
            return JsonResponse({'message': 'error'}, status=400)

class BoardView(View):
    def post(self , request):
        data    = json.loads(request.body)
        title   = data.get('title' , None)
        content = data.get('content' , None)
        try:
            if title and content:
                Memo(
                    title   = title,
                    content = content
                ).save()

                return HttpResponse(status=200)

        except TypeError:
            return HttpResponse(status=400)

        except Exception as  e:
            return JsonResponse({"ERROR" : e},status=400)

    def get(self , request):
        memo = Memo.objects.values()
        return JsonResponse({"data":list(memo)} , status=200)


class BoardDetailView(View):
    def post(self , request , memo_id):
        data      = json.loads(request.body)
        title     = data.get('title'   , None)
        content   = data.get('content' , None)
        memo_data = Memo.objects.get(id = memo_id)

        try :
            if title and content:
                memo_data.title   = title

main/blog/templates/base.html
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Django_book</title>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <!-- bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
        .container {
            margin: 2rem auto;
        }

        h1 {
            padding: 2rem 0;
            display: inline;
        }

        .r_buttons {
            display: inline-block;
            float: right;
        }

        .l_buttons {
            clear: both;
            float: left;
        }

        .table {
            margin: 1rem 0;
        }

        .p_content {
            padding: 2rem;
        }

        label {
            display: block;
        }

        #id_title {
            cols: 40;
        }

        textarea {
            cols: 40;
            rows: 40;
        }

        button, #c_buttons {
            margin: 2rem 0;
        }

        a:hover {
            text-decoration: none
        }

        #s_buttons {
            float: right;
        }

        .search_bar {
            border: 1px solid black;
            border-radius: 10px;
            padding: 8px;
            margin: 10px;
        }

        a:hover {
            color: #86cfda;
        }

        .comment_box {
            border: 1px solid gray;
            border-radius: 10px;
        }





    </style>
</head>
<body>

<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-info">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link active" href="{% url 'logout' %}">로그아웃</a>
            <a class="nav-item nav-link active" href="{% url 'home' %}">글목록</a>
            <a class="nav-item nav-link active" href="{% url 'kyobo' %}">베스트셀러</a>
            <a class="nav-item nav-link active" href="{% url 'book_search' %}">책검색</a>
            <a class="nav-item nav-link active" href="{% url 'book_api' %}">book_api</a>
            <a class="nav-item nav-link active" href="{% url 'covid_api' %}">covid_api</a>
        </div>
        <b style="color:white;">{{ email }}</b>님
    </div>
</nav>

{% block content %}
{% endblock %}

<!-- bootstrap -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>
</html>

main/blog/templates/book_search.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div style="margin:20px; text-align:center;">
    <h1>책 검색</h1>
</div>

<div class="table-responsive container" style="width:1000px;">
    <form action="{% url 'book_search' %}" method="GET">
        <input class="search_bar" type="text" name="input_search" placeholder="검색">
<!--        <input class="btn btn-outline-secondary" type="submit" value="검색">-->
    </form>
</div>

<div class="table-responsive container" style="width:1000px; text-align:center;">
    {% for item in items %}
    <table class="table">
        <thead class="table-info">
        <tr>
            <th width="30%">이미지</th>
            <th width="30%">제목</th>
            <th width="30%">저자</th>
            <th width="30%">가격</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <img src="{{item.image}}" alt="" width="110" height="150">
            </td>
            <td>
                <a href="https://search.kyobobook.co.kr/web/search?vPstrKeyWord={{ item.title |striptags }}&orderClick=LAG">
                    {{ item.title|safe }}
                </a>
            </td>
            <td>
                {{ item.author }}
            </td>
            <td>
                {% load humanize %}
                {{ item.price | intcomma }}원
            </td>
        </tr>
        </tbody>
    </table>
    {% endfor %}
</div>
{% endblock content %}

main/blog/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container table-responsive">
    <h1>메모장</h1>
    <!------------------ display search ------------------------>
    <div style="width:200px; margin-top:10px; margin-bottom:10px;">
        <form action="{% url 'home' %}" method="GET" autocomplete="off">
            <input class="form-control" type="text" name="search" value="{{search_data.title}}" placeholder="검색">
        </form>
    </div>
    <!------------------ display posts list------------------------>

    <table class="table">
        <thead class="table-info">
        <tr>
            <th scope="col" width="15%">번호</th>
            <th scope="col">작성자</th>
            <th scope="col">제목</th>
            <th scope="col" width="25%">저자</th>
            <th scope="col">작성날짜</th>
        </tr>
        </thead>
        <tbody>
        {% for post in posts %}
        <tr>
            <td>{{ forloop.counter}}</td>
            <th>{{ post.writer }}</th>
            <td>
                <a href="{% url 'detail' post.pk %}">
                    {{ post.title|truncatechars:20 }}
                </a>
            </td>
            <td>{{ post.author }}</td>
            <td>{{ post.date }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="http://localhost:8000/blog/create/" class="btn btn-info"
       style="margin-top:10px; margin-bottom:10px; float:right;">
        작성
    </a>

    {% if posts.has_other_pages %}
    <ul class="pagination container" style="justify-content: center;">
        <!-- 제일 처음으로 가기 -->
        {% if posts.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1"> << </a></li>
        {% else %}
            <li class="page-item disabled"><span class="page-link"> << </span></li>
        {% endif %}
        <!-- 이전페이지 -->
        {% if posts.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}"><</a></li>
        {% else %}
            <li class="page-item disabled"><span class="page-link"> < </span></li>
        {% endif %}

        <!-- 페이징 숫자 -->
        {% for i in posts.paginator.page_range %}
            {% if posts.number == i %}
                <li class="page-item active"><span class="page-link">{{ i }} <span
                        class="sr-only">(current)</span></span></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}

        <!-- 다음페이지 -->
        {% if posts.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}"> > </a></li>
        {% else %}
        <li class="page-item disabled"><span class="page-link"> > </span></li>
        {% endif %}

        <!-- 끝 페이지 -->
        {% if posts.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ posts.paginator.num_pages  }}"> >> </a></li>
        {% else %}
            <li class="page-item disabled"><span class="page-link"> >> </span></li>
        {% endif %}
    </ul>
    {% endif %}
    </span>
    {% endblock content %}
</div>

main/blog/templates/kyobo.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div style="margin:20px; text-align:center;">
    <h1>교보문고 베스트셀러</h1>
</div>
<div class="table-responsive container" style="width:1000px; text-align:center;">
    {% for item in kyobo_list %}
    <table class="table">
        <thead class="table-info">
        <tr>
            <th width="25%">이미지</th>
            <th width="25%">제목</th>
            <th width="25%">저자</th>
            <th width="25%">가격</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <img src="{{item.image}}" alt="" width="110" height="150">
            </td>
            <td>
                <a href="https://search.kyobobook.co.kr/web/search?vPstrKeyWord={{ item.title }}&orderClick=LAG">
                    {{ item.title}}
                </a>
            </td>
            <td>
                {{ item.author }}
            </td>
            <td>
                {{ item.original_price }}원
            </td>
        </tr>
        </tbody>
    </table>
    {% endfor %}
</div>
{% endblock content %}

main/blog/templates/postcreate.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">

    <h4 style="margin-left:20px; text-align:center">메모</h4>
    <hr/>
    <div style="text-align:center;">
        <form method="post" class="post-form" action="">
            {% csrf_token %}
            {{form.title}}
            {{form.author}}
            <center>
                <div style="width:100%;">
                    {{form.content}}
                </div>
            </center>
            <input type="submit" value="등록하기" class="btn btn-info" style="float:right;">
        </form>
    </div>
</div>

{% endblock content %}

main/blog/templates/postdetail.html
{% extends "base.html" %}
{% load static %}
{% block content %}



<div class="container">
    <h1>메모장</h1>

    <table class="table">
        <thead>
        <!--        border border-info mh-100-->
        <div class="card-body">
            <div class="rounded">
                <h4><b>제목 :</b> {{ post.title }}</h4>
                <h4><b>저자 :</b> {{ post.author }}</h4>
                <h4><b>작성자 :</b> {{ post.writer }}</h4>
            </div>
            <div class="table-responsive rounded container ">
                {{ post.content|linebreaksbr }}
            </div>
        </div>
        </thead>
    </table>
    <!---------------------crud buttons -------------------------------->
    <!------------ back to posts_list ------------>
    <div>
        <a href="{% url 'home' %}">
            <input class="btn btn-info" type="button" value="목록">
        </a>

        <div class="r_buttons">

            <!-- post_update -->
            {% if post.writer == request.session.user %}
            <a href="{% url 'update' post.pk %}">
                <input class="btn btn-warning" type="button" value="수정하기">
            </a>
            {% endif %}

            <!-- post_delete -->

            {% if post.writer == request.session.user %}
            <a href="{% url 'delete' post.pk %}">
                <input class="btn btn-danger" type="button" value="삭제하기">
            </a>
            {% endif %}
        </div>
    </div>
</div>

<!-- 실제 댓글을 화면에 표시해 주는 부분입니다. -->
{% for comment in comments %}
<div class="breadcrumb container" style="position:relative;">
    <div>
        <h5>{{ comment.writer }}</h5> <!-- 작성자 표시 -->
        <p>{{ comment.date }}</p> <!-- 작성날짜 표시 -->
    </div>
    <!-- 작성한 사용자가 아니면 댓글 삭제 버튼이 보이지 않음. -->
    <div style="position:absolute; bottom:0; right:0; margin:10px;">
        {% if comment.writer == request.session.user %}

        <a href="{% url 'comment_delete' pk=comment.pk %}" class="btn btn-danger">삭제</a>
        {% endif %}
    </div>

</div>

{% empty %}
<p style="text-align:center; padding:15px;">댓글 없습니다..</p>
{% endfor %}

<!-- 댓글 작성히는 부분-->
<!-- form을 이용해서 django view에 데이터를 전송하는 경우 아래와 같은 템플릿 문법으로 view와 연결된 url를 지정 가능하다.-->
<div class="container">
    <form action="{% url 'comment_create' pk=post.pk %}" method="POST">
        {% csrf_token %}  <!-- XSS 공격 방지를 위해 랜덤 토큰을 추가한다. -->
        {{ comment_form }} <!-- 댓글 폼 생성 -->
        {{ comment }}
        <input type="submit" value="작성" class="btn btn-info"
               style="float:right; margin-top:-4.5em; margin-right:1em;">
    </form>
</div>
{% endblock content %}

main/blog/templates/postupdate.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <h4 style="margin-left:20px; text-align:center">메모 update</h4>
    <hr/>
    <div style="text-align:center;">
        <form method="post" class="post-form" action="">
            {% csrf_token %}
            {{form.title}}
            {{form.author}}
                <div style="width:100%;">
                    {{form.content}}
                </div>
            <input type="submit" class="btn btn-info" value="등록하기" style="float:right;">
        </form>
    </div>
</div>

{% endblock content %}